export type Choice = "a" | "b" | "c" | "d";

export type MCQ = {
  id: number;
  topic: string;
  question: string;
  options: Record<Choice, string>;
  answer: Choice;
  explanation: string;
};

export type Essay = {
  id: number;
  topic: string;
  prompt: string;
  hint: string;
  keywords: string[];
  sample: string;
};

export const MCQ_QUESTIONS: MCQ[] = [
  {
    id: 1,
    topic: "Vocabulary",
    question: "The doctor works in a ....",
    options: { a: "library", b: "hospital", c: "bakery", d: "garage" },
    answer: "b",
    explanation:
      "Dokter bekerja di rumah sakit (hospital). Library = perpustakaan, bakery = toko roti, garage = garasi.",
  },
  {
    id: 2,
    topic: "Vocabulary",
    question: "My father is very .... He never gets angry easily.",
    options: { a: "patient", b: "lazy", c: "noisy", d: "dirty" },
    answer: "a",
    explanation:
      "'Never gets angry easily' (tidak mudah marah) berarti sabar = patient. Lazy = malas, noisy = berisik, dirty = kotor.",
  },
  {
    id: 3,
    topic: "Vocabulary",
    question: "The opposite of 'expensive' is ....",
    options: { a: "rich", b: "large", c: "cheap", d: "heavy" },
    answer: "c",
    explanation:
      "Lawan kata 'expensive' (mahal) adalah 'cheap' (murah). Rich = kaya, large = besar, heavy = berat.",
  },
  {
    id: 4,
    topic: "Vocabulary",
    question: "We use a .... to cut the paper.",
    options: { a: "spoon", b: "ruler", c: "broom", d: "pair of scissors" },
    answer: "d",
    explanation:
      "Kita memakai gunting (a pair of scissors) untuk memotong kertas. Spoon = sendok, ruler = penggaris, broom = sapu.",
  },
  {
    id: 5,
    topic: "Grammar",
    question: "Rina and I .... students of SD Nusantara.",
    options: { a: "am", b: "is", c: "are", d: "be" },
    answer: "c",
    explanation:
      "Subjek 'Rina and I' = 'we' (jamak), jadi to be yang tepat adalah 'are'. 'Am' hanya untuk I, 'is' untuk tunggal.",
  },
  {
    id: 6,
    topic: "Grammar",
    question: "There .... many books on the shelf.",
    options: { a: "is", b: "are", c: "was", d: "am" },
    answer: "b",
    explanation: "'Many books' bersifat jamak (plural), sehingga digunakan 'there are'.",
  },
  {
    id: 7,
    topic: "Grammar",
    question: "Choose the correct sentence!",
    options: {
      a: "She go to school every day.",
      b: "She goes to school every day.",
      c: "She going to school every day.",
      d: "She gone to school every day.",
    },
    answer: "b",
    explanation:
      "Simple Present Tense: subjek orang ketiga tunggal (she/he/it) mendapat kata kerja + s/es → 'She goes'.",
  },
  {
    id: 8,
    topic: "Grammar",
    question: "The cat is sleeping .... the table.",
    options: { a: "under", b: "of", c: "and", d: "but" },
    answer: "a",
    explanation:
      "Dibutuhkan preposisi tempat; 'under the table' = di bawah meja. 'Of', 'and', dan 'but' bukan preposisi tempat.",
  },
  {
    id: 9,
    topic: "Tenses",
    question: "Look! The children .... football in the yard now.",
    options: { a: "play", b: "played", c: "are playing", d: "have play" },
    answer: "c",
    explanation:
      "Kata 'Look!' dan 'now' menandakan Present Continuous Tense: to be + V-ing → 'are playing'.",
  },
  {
    id: 10,
    topic: "Tenses",
    question: "Yesterday, we .... to the zoo with our teacher.",
    options: { a: "go", b: "goes", c: "going", d: "went" },
    answer: "d",
    explanation:
      "'Yesterday' menandakan Simple Past Tense; bentuk lampau (V2) dari 'go' adalah 'went'.",
  },
  {
    id: 11,
    topic: "Tenses",
    question: "My mother .... the floor every morning.",
    options: { a: "sweeps", b: "sweep", c: "swept", d: "sweeping" },
    answer: "a",
    explanation:
      "'Every morning' = kebiasaan (Simple Present). Subjek 'my mother' (she) memakai V1+s → 'sweeps'.",
  },
  {
    id: 12,
    topic: "Tenses",
    question: "I .... my homework last night.",
    options: { a: "do", b: "did", c: "does", d: "doing" },
    answer: "b",
    explanation:
      "'Last night' menandakan Simple Past Tense; bentuk lampau dari 'do' adalah 'did'.",
  },
  {
    id: 13,
    topic: "Tenses",
    question: "They .... a movie in the living room at the moment.",
    options: { a: "watch", b: "watched", c: "watches", d: "are watching" },
    answer: "d",
    explanation:
      "'At the moment' = sedang berlangsung sekarang → Present Continuous: 'are watching'.",
  },
  {
    id: 14,
    topic: "Pronouns",
    question: "Andi is my brother. .... is ten years old.",
    options: { a: "She", b: "He", c: "It", d: "They" },
    answer: "b",
    explanation:
      "Andi adalah laki-laki (brother), kata ganti subjeknya adalah 'He'. She = perempuan, It = benda/hewan.",
  },
  {
    id: 15,
    topic: "Pronouns",
    question: "This book is mine. Please give it to ....",
    options: { a: "I", b: "my", c: "me", d: "mine" },
    answer: "c",
    explanation:
      "Setelah preposisi 'to' dipakai object pronoun; bentuk objek dari 'I' adalah 'me'.",
  },
  {
    id: 16,
    topic: "Pronouns",
    question: "Sinta and Dewi are sisters. .... house is near the market.",
    options: { a: "Their", b: "Them", c: "They", d: "Theirs" },
    answer: "a",
    explanation:
      "Dibutuhkan possessive adjective sebelum kata benda 'house'; milik mereka = 'their'.",
  },
  {
    id: 17,
    topic: "Pronouns",
    question: "Look at the bird! .... wings are beautiful.",
    options: { a: "His", b: "Her", c: "Its", d: "Our" },
    answer: "c",
    explanation:
      "Burung adalah hewan, kata ganti kepemilikannya adalah 'its'. His = milik laki-laki, Her = milik perempuan.",
  },
  {
    id: 18,
    topic: "Modals",
    question: "You .... wash your hands before eating.",
    options: { a: "should", b: "shall not", c: "may not", d: "would" },
    answer: "a",
    explanation:
      "Mencuci tangan sebelum makan adalah nasihat/saran → gunakan 'should' (sebaiknya).",
  },
  {
    id: 19,
    topic: "Modals",
    question: "Birds .... fly, but fish cannot.",
    options: { a: "must", b: "can", c: "should", d: "may not" },
    answer: "b",
    explanation:
      "Menyatakan kemampuan (ability) → gunakan 'can'. Burung bisa terbang, ikan tidak bisa.",
  },
  {
    id: 20,
    topic: "Modals",
    question: "Students .... not come late to school.",
    options: { a: "can", b: "will", c: "must", d: "may" },
    answer: "c",
    explanation:
      "Aturan/larangan tegas memakai 'must not' (tidak boleh). Siswa tidak boleh datang terlambat.",
  },
  {
    id: 21,
    topic: "Modals",
    question: '".... you help me carry this box, please?"',
    options: { a: "Could", b: "Did", c: "Was", d: "Am" },
    answer: "a",
    explanation:
      "Permintaan tolong yang sopan (polite request) diawali 'Could you ...?'.",
  },
  {
    id: 22,
    topic: "Reading",
    question:
      "Read: 'Every Sunday, Bima and his family clean the garden. Bima waters the flowers while his father cuts the grass.' What does Bima do?",
    options: {
      a: "He cuts the grass.",
      b: "He waters the flowers.",
      c: "He sweeps the floor.",
      d: "He plants the trees.",
    },
    answer: "b",
    explanation:
      "Teks menyebutkan 'Bima waters the flowers' = Bima menyiram bunga. Ayahnya yang memotong rumput.",
  },
  {
    id: 23,
    topic: "Reading",
    question:
      "Read: 'Every Sunday, Bima and his family clean the garden.' When do they clean the garden?",
    options: { a: "On Monday", b: "On Friday", c: "On Sunday", d: "Every night" },
    answer: "c",
    explanation: "Kalimat pertama jelas menyebut 'Every Sunday' = setiap hari Minggu.",
  },
  {
    id: 24,
    topic: "Descriptive Text",
    question:
      "Read: 'My rabbit is small. It has soft white fur and long ears. It likes eating carrots.' What is the text about?",
    options: { a: "A cat", b: "A rabbit", c: "A carrot", d: "A farm" },
    answer: "b",
    explanation:
      "Seluruh kalimat mendeskripsikan kelinci (rabbit): ukuran, bulu, telinga, dan makanannya.",
  },
  {
    id: 25,
    topic: "Descriptive Text",
    question: "From the text above, the rabbit's fur is ....",
    options: { a: "hard and black", b: "soft and white", c: "long and grey", d: "short and brown" },
    answer: "b",
    explanation: "Teks menyebut 'soft white fur' = bulu yang lembut dan putih.",
  },
  {
    id: 26,
    topic: "Descriptive Text",
    question: "Which sentence describes a person's appearance?",
    options: {
      a: "He goes to school by bus.",
      b: "He has curly hair and a round face.",
      c: "He played football yesterday.",
      d: "He will study tonight.",
    },
    answer: "b",
    explanation:
      "'Curly hair and a round face' (rambut keriting dan wajah bulat) adalah ciri penampilan fisik seseorang.",
  },
  {
    id: 27,
    topic: "Narrative Text",
    question:
      "Read: 'Once upon a time, a clever mouse deer was trapped in a hole. A wise elephant helped him get out.' Who helped the mouse deer?",
    options: { a: "A tiger", b: "A farmer", c: "An elephant", d: "A crocodile" },
    answer: "c",
    explanation:
      "Teks menyebut 'A wise elephant helped him' = seekor gajah bijaksana yang menolong kancil.",
  },
  {
    id: 28,
    topic: "Narrative Text",
    question: "The story above usually begins with the phrase ....",
    options: { a: "Once upon a time", b: "First of all", c: "In conclusion", d: "Dear friend" },
    answer: "a",
    explanation:
      "Cerita naratif (dongeng) khas diawali 'Once upon a time' (pada zaman dahulu kala).",
  },
  {
    id: 29,
    topic: "Functional Text",
    question: "'NO PARKING' — This sign means we may not .... in that area.",
    options: { a: "walk", b: "park our vehicle", c: "take a photo", d: "sit down" },
    answer: "b",
    explanation:
      "Rambu 'NO PARKING' berarti dilarang memarkir kendaraan di area tersebut.",
  },
  {
    id: 30,
    topic: "Functional Text",
    question:
      "Announcement: 'The flag ceremony will be held on Monday at 07.00 a.m. in the school yard.' Where will the ceremony be held?",
    options: {
      a: "In the classroom",
      b: "In the library",
      c: "In the school yard",
      d: "At the market",
    },
    answer: "c",
    explanation:
      "Pengumuman menyebutkan upacara diadakan 'in the school yard' = di halaman sekolah.",
  },

  {
    id: 101,
    topic: "Vocabulary",
    question: "The word 'enormous' means ...",
    options: { a: "very small", b: "very big", c: "very weak", d: "very slow" },
    answer: "b",
    explanation: "Jawaban benar: B. very big (Vocabulary)",
  },
  {
    id: 102,
    topic: "Vocabulary",
    question: "The opposite of 'ancient' is ...",
    options: { a: "modern", b: "old", c: "broken", d: "dirty" },
    answer: "a",
    explanation: "Jawaban benar: A. modern (Vocabulary)",
  },
  {
    id: 103,
    topic: "Vocabulary",
    question: "A person who designs buildings is an ...",
    options: { a: "artist", b: "architect", c: "athlete", d: "actor" },
    answer: "b",
    explanation: "Jawaban benar: B. architect (Vocabulary)",
  },
  {
    id: 104,
    topic: "Vocabulary",
    question: "If something is 'fragile', it can be ...",
    options: { a: "easily broken", b: "easily eaten", c: "easily found", d: "easily grown" },
    answer: "a",
    explanation: "Jawaban benar: A. easily broken (Vocabulary)",
  },
  {
    id: 105,
    topic: "Vocabulary",
    question: "Someone who is 'generous' likes to ...",
    options: { a: "help and give to others", b: "hide from everyone", c: "arrive late", d: "make loud noises" },
    answer: "a",
    explanation: "Jawaban benar: A. help and give to others (Vocabulary)",
  },
  {
    id: 106,
    topic: "Vocabulary",
    question: "The opposite of 'polite' is ...",
    options: { a: "friendly", b: "rude", c: "quiet", d: "clever" },
    answer: "b",
    explanation: "Jawaban benar: B. rude (Vocabulary)",
  },
  {
    id: 107,
    topic: "Vocabulary",
    question: "A place where you can borrow books is a ...",
    options: { a: "bakery", b: "library", c: "stadium", d: "garage" },
    answer: "b",
    explanation: "Jawaban benar: B. library (Vocabulary)",
  },
  {
    id: 108,
    topic: "Vocabulary",
    question: "A person who flies an airplane is a ...",
    options: { a: "pilot", b: "sailor", c: "farmer", d: "dentist" },
    answer: "a",
    explanation: "Jawaban benar: A. pilot (Vocabulary)",
  },
  {
    id: 109,
    topic: "Vocabulary",
    question: "The word 'rapid' is closest in meaning to ...",
    options: { a: "slow", b: "fast", c: "heavy", d: "weak" },
    answer: "b",
    explanation: "Jawaban benar: B. fast (Vocabulary)",
  },
  {
    id: 110,
    topic: "Vocabulary",
    question: "If a room is 'spacious', it is ...",
    options: { a: "very crowded", b: "full of noise", c: "large and roomy", d: "very dark" },
    answer: "c",
    explanation: "Jawaban benar: C. large and roomy (Vocabulary)",
  },
  {
    id: 111,
    topic: "Vocabulary",
    question: "A person who repairs cars is a ...",
    options: { a: "mechanic", b: "chef", c: "cashier", d: "journalist" },
    answer: "a",
    explanation: "Jawaban benar: A. mechanic (Vocabulary)",
  },
  {
    id: 112,
    topic: "Vocabulary",
    question: "The opposite of 'victory' is ...",
    options: { a: "success", b: "prize", c: "defeat", d: "celebration" },
    answer: "c",
    explanation: "Jawaban benar: C. defeat (Vocabulary)",
  },
  {
    id: 113,
    topic: "Vocabulary",
    question: "'Purchase' means ...",
    options: { a: "buy", b: "sell", c: "borrow", d: "break" },
    answer: "a",
    explanation: "Jawaban benar: A. buy (Vocabulary)",
  },
  {
    id: 114,
    topic: "Vocabulary",
    question: "A person who grows crops is usually a ...",
    options: { a: "farmer", b: "pilot", c: "doctor", d: "guard" },
    answer: "a",
    explanation: "Jawaban benar: A. farmer (Vocabulary)",
  },
  {
    id: 115,
    topic: "Vocabulary",
    question: "The word 'delicious' describes food that ...",
    options: { a: "tastes very good", b: "is very cold", c: "is very expensive", d: "is very large" },
    answer: "a",
    explanation: "Jawaban benar: A. tastes very good (Vocabulary)",
  },
  {
    id: 116,
    topic: "Vocabulary",
    question: "The opposite of 'dangerous' is ...",
    options: { a: "safe", b: "brave", c: "strong", d: "busy" },
    answer: "a",
    explanation: "Jawaban benar: A. safe (Vocabulary)",
  },
  {
    id: 117,
    topic: "Vocabulary",
    question: "A 'journey' is ...",
    options: { a: "a trip from one place to another", b: "a school subject", c: "a kind of food", d: "a piece of furniture" },
    answer: "a",
    explanation: "Jawaban benar: A. a trip from one place to another (Vocabulary)",
  },
  {
    id: 118,
    topic: "Vocabulary",
    question: "If you are 'exhausted', you are ...",
    options: { a: "very tired", b: "very hungry", c: "very angry", d: "very early" },
    answer: "a",
    explanation: "Jawaban benar: A. very tired (Vocabulary)",
  },
  {
    id: 119,
    topic: "Vocabulary",
    question: "The word 'assist' means ...",
    options: { a: "help", b: "leave", c: "forget", d: "choose" },
    answer: "a",
    explanation: "Jawaban benar: A. help (Vocabulary)",
  },
  {
    id: 120,
    topic: "Vocabulary",
    question: "A person who takes care of sick animals is a ...",
    options: { a: "veterinarian", b: "architect", c: "librarian", d: "musician" },
    answer: "a",
    explanation: "Jawaban benar: A. veterinarian (Vocabulary)",
  },
  {
    id: 121,
    topic: "Grammar",
    question: "My brother ___ football every Sunday.",
    options: { a: "play", b: "plays", c: "played", d: "playing" },
    answer: "b",
    explanation: "Jawaban benar: B. plays (Grammar)",
  },
  {
    id: 122,
    topic: "Grammar",
    question: "There ___ a pencil on the desk.",
    options: { a: "is", b: "are", c: "am", d: "be" },
    answer: "a",
    explanation: "Jawaban benar: A. is (Grammar)",
  },
  {
    id: 123,
    topic: "Grammar",
    question: "There ___ five students in the room.",
    options: { a: "is", b: "am", c: "are", d: "be" },
    answer: "c",
    explanation: "Jawaban benar: C. are (Grammar)",
  },
  {
    id: 124,
    topic: "Grammar",
    question: "She ___ not like spicy food.",
    options: { a: "do", b: "does", c: "is", d: "are" },
    answer: "b",
    explanation: "Jawaban benar: B. does (Grammar)",
  },
  {
    id: 125,
    topic: "Grammar",
    question: "They ___ happy today.",
    options: { a: "is", b: "am", c: "are", d: "be" },
    answer: "c",
    explanation: "Jawaban benar: C. are (Grammar)",
  },
  {
    id: 126,
    topic: "Grammar",
    question: "Rina and Siti ___ best friends.",
    options: { a: "is", b: "am", c: "are", d: "was" },
    answer: "c",
    explanation: "Jawaban benar: C. are (Grammar)",
  },
  {
    id: 127,
    topic: "Grammar",
    question: "My father ___ a teacher.",
    options: { a: "are", b: "am", c: "is", d: "be" },
    answer: "c",
    explanation: "Jawaban benar: C. is (Grammar)",
  },
  {
    id: 128,
    topic: "Grammar",
    question: "I ___ two brothers.",
    options: { a: "has", b: "have", c: "having", d: "had" },
    answer: "b",
    explanation: "Jawaban benar: B. have (Grammar)",
  },
  {
    id: 129,
    topic: "Grammar",
    question: "Budi ___ a new bicycle.",
    options: { a: "have", b: "having", c: "has", d: "are" },
    answer: "c",
    explanation: "Jawaban benar: C. has (Grammar)",
  },
  {
    id: 130,
    topic: "Grammar",
    question: "Choose the correct sentence.",
    options: { a: "She don't like tea.", b: "She doesn't like tea.", c: "She doesn't likes tea.", d: "She not likes tea." },
    answer: "b",
    explanation: "Jawaban benar: B. She doesn't like tea. (Grammar)",
  },
  {
    id: 131,
    topic: "Grammar",
    question: "Choose the correct sentence.",
    options: { a: "They is students.", b: "They am students.", c: "They are students.", d: "They be students." },
    answer: "c",
    explanation: "Jawaban benar: C. They are students. (Grammar)",
  },
  {
    id: 132,
    topic: "Grammar",
    question: "The cat is ___ the table.",
    options: { a: "on", b: "at", c: "to", d: "from" },
    answer: "a",
    explanation: "Jawaban benar: A. on (Grammar)",
  },
  {
    id: 133,
    topic: "Grammar",
    question: "We go to school ___ Monday.",
    options: { a: "in", b: "on", c: "at", d: "by" },
    answer: "b",
    explanation: "Jawaban benar: B. on (Grammar)",
  },
  {
    id: 134,
    topic: "Grammar",
    question: "My birthday is ___ July.",
    options: { a: "on", b: "at", c: "in", d: "from" },
    answer: "c",
    explanation: "Jawaban benar: C. in (Grammar)",
  },
  {
    id: 135,
    topic: "Grammar",
    question: "The children are ___ the classroom.",
    options: { a: "under", b: "in", c: "between", d: "from" },
    answer: "b",
    explanation: "Jawaban benar: B. in (Grammar)",
  },
  {
    id: 136,
    topic: "Grammar",
    question: "This book is ___ than that book.",
    options: { a: "interesting", b: "more interesting", c: "most interesting", d: "interest" },
    answer: "b",
    explanation: "Jawaban benar: B. more interesting (Grammar)",
  },
  {
    id: 137,
    topic: "Grammar",
    question: "Ali is ___ than his brother.",
    options: { a: "tall", b: "taller", c: "tallest", d: "more tall" },
    answer: "b",
    explanation: "Jawaban benar: B. taller (Grammar)",
  },
  {
    id: 138,
    topic: "Grammar",
    question: "This is the ___ mountain in the area.",
    options: { a: "high", b: "higher", c: "highest", d: "more high" },
    answer: "c",
    explanation: "Jawaban benar: C. highest (Grammar)",
  },
  {
    id: 139,
    topic: "Grammar",
    question: "I have ___ apple and two bananas.",
    options: { a: "a", b: "an", c: "the", d: "some" },
    answer: "b",
    explanation: "Jawaban benar: B. an (Grammar)",
  },
  {
    id: 140,
    topic: "Grammar",
    question: "She bought ___ new bag yesterday.",
    options: { a: "a", b: "an", c: "any", d: "much" },
    answer: "a",
    explanation: "Jawaban benar: A. a (Grammar)",
  },
  {
    id: 141,
    topic: "Tenses - Present",
    question: "I ___ breakfast at 6 a.m. every day.",
    options: { a: "eat", b: "ate", c: "eating", d: "eaten" },
    answer: "a",
    explanation: "Jawaban benar: A. eat (Tenses - Present)",
  },
  {
    id: 142,
    topic: "Tenses - Present",
    question: "She ___ to school by bus every morning.",
    options: { a: "go", b: "goes", c: "went", d: "going" },
    answer: "b",
    explanation: "Jawaban benar: B. goes (Tenses - Present)",
  },
  {
    id: 143,
    topic: "Tenses - Present",
    question: "They ___ English twice a week.",
    options: { a: "study", b: "studies", c: "studied", d: "studying" },
    answer: "a",
    explanation: "Jawaban benar: A. study (Tenses - Present)",
  },
  {
    id: 144,
    topic: "Tenses - Present",
    question: "My mother ___ coffee every morning.",
    options: { a: "drink", b: "drinks", c: "drank", d: "drinking" },
    answer: "b",
    explanation: "Jawaban benar: B. drinks (Tenses - Present)",
  },
  {
    id: 145,
    topic: "Tenses - Present",
    question: "The sun ___ in the east.",
    options: { a: "rise", b: "rises", c: "rose", d: "rising" },
    answer: "b",
    explanation: "Jawaban benar: B. rises (Tenses - Present)",
  },
  {
    id: 146,
    topic: "Tenses - Present",
    question: "Water ___ at 100 degrees Celsius.",
    options: { a: "boil", b: "boils", c: "boiled", d: "boiling" },
    answer: "b",
    explanation: "Jawaban benar: B. boils (Tenses - Present)",
  },
  {
    id: 147,
    topic: "Tenses - Present",
    question: "He ___ his room every Saturday.",
    options: { a: "clean", b: "cleans", c: "cleaned", d: "cleaning" },
    answer: "b",
    explanation: "Jawaban benar: B. cleans (Tenses - Present)",
  },
  {
    id: 148,
    topic: "Tenses - Present",
    question: "We ___ TV after dinner.",
    options: { a: "watch", b: "watches", c: "watched", d: "watching" },
    answer: "a",
    explanation: "Jawaban benar: A. watch (Tenses - Present)",
  },
  {
    id: 149,
    topic: "Tenses - Present",
    question: "Sinta ___ a novel before bed.",
    options: { a: "read", b: "reads", c: "reading", d: "readed" },
    answer: "b",
    explanation: "Jawaban benar: B. reads (Tenses - Present)",
  },
  {
    id: 150,
    topic: "Tenses - Present",
    question: "The dog ___ loudly at strangers.",
    options: { a: "bark", b: "barks", c: "barked", d: "barking" },
    answer: "b",
    explanation: "Jawaban benar: B. barks (Tenses - Present)",
  },
  {
    id: 151,
    topic: "Tenses - Present",
    question: "My parents ___ in Surabaya.",
    options: { a: "live", b: "lives", c: "lived", d: "living" },
    answer: "a",
    explanation: "Jawaban benar: A. live (Tenses - Present)",
  },
  {
    id: 152,
    topic: "Tenses - Present",
    question: "Rafi ___ his teeth twice a day.",
    options: { a: "brush", b: "brushes", c: "brushed", d: "brushing" },
    answer: "b",
    explanation: "Jawaban benar: B. brushes (Tenses - Present)",
  },
  {
    id: 153,
    topic: "Tenses - Present",
    question: "Birds ___ in the sky.",
    options: { a: "fly", b: "flies", c: "flew", d: "flying" },
    answer: "a",
    explanation: "Jawaban benar: A. fly (Tenses - Present)",
  },
  {
    id: 154,
    topic: "Tenses - Present",
    question: "A cow ___ grass.",
    options: { a: "eat", b: "eats", c: "ate", d: "eating" },
    answer: "b",
    explanation: "Jawaban benar: B. eats (Tenses - Present)",
  },
  {
    id: 155,
    topic: "Tenses - Present",
    question: "We ___ our teacher carefully.",
    options: { a: "listen to", b: "listens to", c: "listened to", d: "listening to" },
    answer: "a",
    explanation: "Jawaban benar: A. listen to (Tenses - Present)",
  },
  {
    id: 156,
    topic: "Tenses - Present",
    question: "Does your sister ___ English?",
    options: { a: "speaks", b: "speak", c: "spoke", d: "speaking" },
    answer: "b",
    explanation: "Jawaban benar: B. speak (Tenses - Present)",
  },
  {
    id: 157,
    topic: "Tenses - Present",
    question: "Do they ___ football on Friday?",
    options: { a: "plays", b: "play", c: "played", d: "playing" },
    answer: "b",
    explanation: "Jawaban benar: B. play (Tenses - Present)",
  },
  {
    id: 158,
    topic: "Tenses - Present",
    question: "He does not ___ spicy food.",
    options: { a: "likes", b: "like", c: "liked", d: "liking" },
    answer: "b",
    explanation: "Jawaban benar: B. like (Tenses - Present)",
  },
  {
    id: 159,
    topic: "Tenses - Present",
    question: "The library ___ at eight o'clock.",
    options: { a: "open", b: "opens", c: "opened", d: "opening" },
    answer: "b",
    explanation: "Jawaban benar: B. opens (Tenses - Present)",
  },
  {
    id: 160,
    topic: "Tenses - Present",
    question: "My friends ___ me with my homework.",
    options: { a: "help", b: "helps", c: "helped", d: "helping" },
    answer: "a",
    explanation: "Jawaban benar: A. help (Tenses - Present)",
  },
  {
    id: 161,
    topic: "Tenses - Past",
    question: "Yesterday, I ___ to the market.",
    options: { a: "go", b: "goes", c: "went", d: "going" },
    answer: "c",
    explanation: "Jawaban benar: C. went (Tenses - Past)",
  },
  {
    id: 162,
    topic: "Tenses - Past",
    question: "She ___ a letter last night.",
    options: { a: "write", b: "writes", c: "wrote", d: "writing" },
    answer: "c",
    explanation: "Jawaban benar: C. wrote (Tenses - Past)",
  },
  {
    id: 163,
    topic: "Tenses - Past",
    question: "We ___ a movie yesterday.",
    options: { a: "watch", b: "watched", c: "watches", d: "watching" },
    answer: "b",
    explanation: "Jawaban benar: B. watched (Tenses - Past)",
  },
  {
    id: 164,
    topic: "Tenses - Past",
    question: "He ___ his homework two hours ago.",
    options: { a: "finish", b: "finishes", c: "finished", d: "finishing" },
    answer: "c",
    explanation: "Jawaban benar: C. finished (Tenses - Past)",
  },
  {
    id: 165,
    topic: "Tenses - Past",
    question: "They ___ football last Saturday.",
    options: { a: "play", b: "played", c: "plays", d: "playing" },
    answer: "b",
    explanation: "Jawaban benar: B. played (Tenses - Past)",
  },
  {
    id: 166,
    topic: "Tenses - Past",
    question: "My mother ___ dinner at 7 p.m. yesterday.",
    options: { a: "cook", b: "cooks", c: "cooked", d: "cooking" },
    answer: "c",
    explanation: "Jawaban benar: C. cooked (Tenses - Past)",
  },
  {
    id: 167,
    topic: "Tenses - Past",
    question: "I ___ my friend at the library yesterday.",
    options: { a: "meet", b: "meets", c: "met", d: "meeting" },
    answer: "c",
    explanation: "Jawaban benar: C. met (Tenses - Past)",
  },
  {
    id: 168,
    topic: "Tenses - Past",
    question: "Rina ___ a beautiful picture last week.",
    options: { a: "draw", b: "draws", c: "drew", d: "drawing" },
    answer: "c",
    explanation: "Jawaban benar: C. drew (Tenses - Past)",
  },
  {
    id: 169,
    topic: "Tenses - Past",
    question: "The students ___ the classroom yesterday.",
    options: { a: "clean", b: "cleans", c: "cleaned", d: "cleaning" },
    answer: "c",
    explanation: "Jawaban benar: C. cleaned (Tenses - Past)",
  },
  {
    id: 170,
    topic: "Tenses - Past",
    question: "We ___ early this morning.",
    options: { a: "wake up", b: "wakes up", c: "woke up", d: "waking up" },
    answer: "c",
    explanation: "Jawaban benar: C. woke up (Tenses - Past)",
  },
  {
    id: 171,
    topic: "Tenses - Past",
    question: "He ___ a new bag last month.",
    options: { a: "buy", b: "buys", c: "bought", d: "buying" },
    answer: "c",
    explanation: "Jawaban benar: C. bought (Tenses - Past)",
  },
  {
    id: 172,
    topic: "Tenses - Past",
    question: "My father ___ home late last night.",
    options: { a: "come", b: "comes", c: "came", d: "coming" },
    answer: "c",
    explanation: "Jawaban benar: C. came (Tenses - Past)",
  },
  {
    id: 173,
    topic: "Tenses - Past",
    question: "They ___ happy after the competition.",
    options: { a: "are", b: "is", c: "were", d: "be" },
    answer: "c",
    explanation: "Jawaban benar: C. were (Tenses - Past)",
  },
  {
    id: 174,
    topic: "Tenses - Past",
    question: "She ___ at home yesterday.",
    options: { a: "is", b: "was", c: "were", d: "be" },
    answer: "b",
    explanation: "Jawaban benar: B. was (Tenses - Past)",
  },
  {
    id: 175,
    topic: "Tenses - Past",
    question: "I ___ sick last Monday.",
    options: { a: "am", b: "is", c: "was", d: "were" },
    answer: "c",
    explanation: "Jawaban benar: C. was (Tenses - Past)",
  },
  {
    id: 176,
    topic: "Tenses - Past",
    question: "Did you ___ the museum yesterday?",
    options: { a: "visited", b: "visit", c: "visiting", d: "visits" },
    answer: "b",
    explanation: "Jawaban benar: B. visit (Tenses - Past)",
  },
  {
    id: 177,
    topic: "Tenses - Past",
    question: "She did not ___ breakfast this morning.",
    options: { a: "ate", b: "eats", c: "eat", d: "eating" },
    answer: "c",
    explanation: "Jawaban benar: C. eat (Tenses - Past)",
  },
  {
    id: 178,
    topic: "Tenses - Past",
    question: "We ___ many photos during our trip.",
    options: { a: "take", b: "takes", c: "took", d: "taking" },
    answer: "c",
    explanation: "Jawaban benar: C. took (Tenses - Past)",
  },
  {
    id: 179,
    topic: "Tenses - Past",
    question: "The cat ___ under the chair yesterday.",
    options: { a: "sleep", b: "slept", c: "sleeps", d: "sleeping" },
    answer: "b",
    explanation: "Jawaban benar: B. slept (Tenses - Past)",
  },
  {
    id: 180,
    topic: "Tenses - Past",
    question: "My uncle ___ me a gift last week.",
    options: { a: "give", b: "gives", c: "gave", d: "giving" },
    answer: "c",
    explanation: "Jawaban benar: C. gave (Tenses - Past)",
  },
  {
    id: 181,
    topic: "Pronouns",
    question: "Dina is my friend. ___ is very kind.",
    options: { a: "He", b: "She", c: "It", d: "They" },
    answer: "b",
    explanation: "Jawaban benar: B. She (Pronouns)",
  },
  {
    id: 182,
    topic: "Pronouns",
    question: "Rudi is my brother. ___ likes football.",
    options: { a: "He", b: "She", c: "It", d: "We" },
    answer: "a",
    explanation: "Jawaban benar: A. He (Pronouns)",
  },
  {
    id: 183,
    topic: "Pronouns",
    question: "The book is on the table. ___ is new.",
    options: { a: "He", b: "She", c: "It", d: "They" },
    answer: "c",
    explanation: "Jawaban benar: C. It (Pronouns)",
  },
  {
    id: 184,
    topic: "Pronouns",
    question: "Sinta and I are classmates. ___ study together.",
    options: { a: "They", b: "We", c: "You", d: "He" },
    answer: "b",
    explanation: "Jawaban benar: B. We (Pronouns)",
  },
  {
    id: 185,
    topic: "Pronouns",
    question: "Budi and Andi are brothers. ___ live in Jakarta.",
    options: { a: "We", b: "They", c: "He", d: "It" },
    answer: "b",
    explanation: "Jawaban benar: B. They (Pronouns)",
  },
  {
    id: 186,
    topic: "Pronouns",
    question: "My parents are at home. I will call ___.",
    options: { a: "he", b: "she", c: "them", d: "it" },
    answer: "c",
    explanation: "Jawaban benar: C. them (Pronouns)",
  },
  {
    id: 187,
    topic: "Pronouns",
    question: "This is my teacher. I respect ___.",
    options: { a: "her", b: "it", c: "they", d: "we" },
    answer: "a",
    explanation: "Jawaban benar: A. her (Pronouns)",
  },
  {
    id: 188,
    topic: "Pronouns",
    question: "I have a dog. I love ___.",
    options: { a: "him", b: "her", c: "it", d: "them" },
    answer: "c",
    explanation: "Jawaban benar: C. it (Pronouns)",
  },
  {
    id: 189,
    topic: "Pronouns",
    question: "The children are playing. The teacher watches ___.",
    options: { a: "them", b: "him", c: "her", d: "it" },
    answer: "a",
    explanation: "Jawaban benar: A. them (Pronouns)",
  },
  {
    id: 190,
    topic: "Pronouns",
    question: "That bicycle belongs to me. It is ___.",
    options: { a: "mine", b: "my", c: "me", d: "I" },
    answer: "a",
    explanation: "Jawaban benar: A. mine (Pronouns)",
  },
  {
    id: 191,
    topic: "Pronouns",
    question: "This is ___ book. I bought it yesterday.",
    options: { a: "I", b: "me", c: "my", d: "mine" },
    answer: "c",
    explanation: "Jawaban benar: C. my (Pronouns)",
  },
  {
    id: 192,
    topic: "Pronouns",
    question: "Those shoes belong to Ali. They are ___.",
    options: { a: "he", b: "his", c: "him", d: "hers" },
    answer: "b",
    explanation: "Jawaban benar: B. his (Pronouns)",
  },
  {
    id: 193,
    topic: "Pronouns",
    question: "This bag belongs to Sarah. It is ___.",
    options: { a: "hers", b: "her", c: "she", d: "their" },
    answer: "a",
    explanation: "Jawaban benar: A. hers (Pronouns)",
  },
  {
    id: 194,
    topic: "Pronouns",
    question: "We have a house. It is ___ house.",
    options: { a: "our", b: "ours", c: "us", d: "we" },
    answer: "a",
    explanation: "Jawaban benar: A. our (Pronouns)",
  },
  {
    id: 195,
    topic: "Pronouns",
    question: "The students have books. The books are ___.",
    options: { a: "their", b: "theirs", c: "them", d: "they" },
    answer: "b",
    explanation: "Jawaban benar: B. theirs (Pronouns)",
  },
  {
    id: 196,
    topic: "Pronouns",
    question: "Please give the pencil to ___.",
    options: { a: "I", b: "me", c: "my", d: "mine" },
    answer: "b",
    explanation: "Jawaban benar: B. me (Pronouns)",
  },
  {
    id: 197,
    topic: "Pronouns",
    question: "___ am going to school now.",
    options: { a: "Me", b: "My", c: "I", d: "Mine" },
    answer: "c",
    explanation: "Jawaban benar: C. I (Pronouns)",
  },
  {
    id: 198,
    topic: "Pronouns",
    question: "Can ___ help me with this box?",
    options: { a: "you", b: "your", c: "yours", d: "they" },
    answer: "a",
    explanation: "Jawaban benar: A. you (Pronouns)",
  },
  {
    id: 199,
    topic: "Pronouns",
    question: "Tom and I finished the project by ___.",
    options: { a: "ourselves", b: "themselves", c: "himself", d: "herself" },
    answer: "a",
    explanation: "Jawaban benar: A. ourselves (Pronouns)",
  },
  {
    id: 200,
    topic: "Pronouns",
    question: "The girl looked at ___ in the mirror.",
    options: { a: "himself", b: "herself", c: "themselves", d: "ourselves" },
    answer: "b",
    explanation: "Jawaban benar: B. herself (Pronouns)",
  },
  {
    id: 201,
    topic: "Modals",
    question: "You ___ obey the school rules.",
    options: { a: "must", b: "can", c: "may", d: "could" },
    answer: "a",
    explanation: "Jawaban benar: A. must (Modals)",
  },
  {
    id: 202,
    topic: "Modals",
    question: "___ you swim?",
    options: { a: "Must", b: "Can", c: "Should", d: "May" },
    answer: "b",
    explanation: "Jawaban benar: B. Can (Modals)",
  },
  {
    id: 203,
    topic: "Modals",
    question: "You ___ drink enough water every day.",
    options: { a: "should", b: "mustn't", c: "can't", d: "couldn't" },
    answer: "a",
    explanation: "Jawaban benar: A. should (Modals)",
  },
  {
    id: 204,
    topic: "Modals",
    question: "Students ___ not cheat in an exam.",
    options: { a: "must", b: "must", c: "mustn't", d: "can" },
    answer: "c",
    explanation: "Jawaban benar: C. mustn't (Modals)",
  },
  {
    id: 205,
    topic: "Modals",
    question: "We ___ wear uniforms at school.",
    options: { a: "must", b: "can", c: "may", d: "could" },
    answer: "a",
    explanation: "Jawaban benar: A. must (Modals)",
  },
  {
    id: 206,
    topic: "Modals",
    question: "___ I borrow your pencil, please?",
    options: { a: "May", b: "Must", c: "Should", d: "Need" },
    answer: "a",
    explanation: "Jawaban benar: A. May (Modals)",
  },
  {
    id: 207,
    topic: "Modals",
    question: "You ___ be quiet in the library.",
    options: { a: "should", b: "can", c: "may", d: "could" },
    answer: "a",
    explanation: "Jawaban benar: A. should (Modals)",
  },
  {
    id: 208,
    topic: "Modals",
    question: "I ___ ride a bicycle when I was five.",
    options: { a: "could", b: "must", c: "may", d: "should" },
    answer: "a",
    explanation: "Jawaban benar: A. could (Modals)",
  },
  {
    id: 209,
    topic: "Modals",
    question: "It ___ rain tomorrow.",
    options: { a: "may", b: "must", c: "should", d: "can't" },
    answer: "a",
    explanation: "Jawaban benar: A. may (Modals)",
  },
  {
    id: 210,
    topic: "Modals",
    question: "You ___ cross the road when the light is red.",
    options: { a: "must", b: "should", c: "mustn't", d: "can" },
    answer: "c",
    explanation: "Jawaban benar: C. mustn't (Modals)",
  },
  {
    id: 211,
    topic: "Modals",
    question: "We ___ help people who need us.",
    options: { a: "should", b: "couldn't", c: "mustn't", d: "can't" },
    answer: "a",
    explanation: "Jawaban benar: A. should (Modals)",
  },
  {
    id: 212,
    topic: "Modals",
    question: "He ___ speak English very well.",
    options: { a: "can", b: "mustn't", c: "shouldn't", d: "may not" },
    answer: "a",
    explanation: "Jawaban benar: A. can (Modals)",
  },
  {
    id: 213,
    topic: "Modals",
    question: "___ I open the window?",
    options: { a: "May", b: "Must", c: "Should", d: "Need" },
    answer: "a",
    explanation: "Jawaban benar: A. May (Modals)",
  },
  {
    id: 214,
    topic: "Modals",
    question: "You ___ bring your English book tomorrow.",
    options: { a: "should", b: "can't", c: "couldn't", d: "may not" },
    answer: "a",
    explanation: "Jawaban benar: A. should (Modals)",
  },
  {
    id: 215,
    topic: "Modals",
    question: "Visitors ___ enter this room. It is restricted.",
    options: { a: "mustn't", b: "can", c: "should", d: "may" },
    answer: "a",
    explanation: "Jawaban benar: A. mustn't (Modals)",
  },
  {
    id: 216,
    topic: "Modals",
    question: "When I was young, I ___ run very fast.",
    options: { a: "could", b: "must", c: "may", d: "should" },
    answer: "a",
    explanation: "Jawaban benar: A. could (Modals)",
  },
  {
    id: 217,
    topic: "Modals",
    question: "You ___ forget to bring your homework.",
    options: { a: "mustn't", b: "can", c: "may", d: "could" },
    answer: "a",
    explanation: "Jawaban benar: A. mustn't (Modals)",
  },
  {
    id: 218,
    topic: "Modals",
    question: "___ we go to the park after school?",
    options: { a: "Shall", b: "Mustn't", c: "Could not", d: "Need" },
    answer: "a",
    explanation: "Jawaban benar: A. Shall (Modals)",
  },
  {
    id: 219,
    topic: "Modals",
    question: "She ___ be at home; the lights are on.",
    options: { a: "may", b: "must", c: "can't", d: "shouldn't" },
    answer: "a",
    explanation: "Jawaban benar: A. may (Modals)",
  },
  {
    id: 220,
    topic: "Modals",
    question: "You ___ ask your teacher if you do not understand.",
    options: { a: "should", b: "mustn't", c: "can't", d: "couldn't" },
    answer: "a",
    explanation: "Jawaban benar: A. should (Modals)",
  },
  {
    id: 221,
    topic: "Reading",
    question: "What time does Arman wake up?  Passage: Every morning, Arman wakes up at five o'clock. He helps his mother prepare breakfast before going to school. He usually walks to school because it is near his house.",
    options: { a: "At four o'clock", b: "At five o'clock", c: "At six o'clock", d: "At seven o'clock" },
    answer: "b",
    explanation: "Jawaban benar: B. At five o'clock (Reading)",
  },
  {
    id: 222,
    topic: "Reading",
    question: "Whom does Arman help?  Passage: Every morning, Arman wakes up at five o'clock. He helps his mother prepare breakfast before going to school. He usually walks to school because it is near his house.",
    options: { a: "His father", b: "His teacher", c: "His mother", d: "His brother" },
    answer: "c",
    explanation: "Jawaban benar: C. His mother (Reading)",
  },
  {
    id: 223,
    topic: "Reading",
    question: "What does he help prepare?  Passage: Every morning, Arman wakes up at five o'clock. He helps his mother prepare breakfast before going to school. He usually walks to school because it is near his house.",
    options: { a: "Lunch", b: "Breakfast", c: "Dinner", d: "Snacks" },
    answer: "b",
    explanation: "Jawaban benar: B. Breakfast (Reading)",
  },
  {
    id: 224,
    topic: "Reading",
    question: "How does he usually go to school?  Passage: Every morning, Arman wakes up at five o'clock. He helps his mother prepare breakfast before going to school. He usually walks to school because it is near his house.",
    options: { a: "By bus", b: "By car", c: "By bicycle", d: "On foot" },
    answer: "d",
    explanation: "Jawaban benar: D. On foot (Reading)",
  },
  {
    id: 225,
    topic: "Reading",
    question: "Why does he walk to school?  Passage: Every morning, Arman wakes up at five o'clock. He helps his mother prepare breakfast before going to school. He usually walks to school because it is near his house.",
    options: { a: "It is far away.", b: "He dislikes buses.", c: "It is near his house.", d: "His bicycle is broken." },
    answer: "c",
    explanation: "Jawaban benar: C. It is near his house. (Reading)",
  },
  {
    id: 226,
    topic: "Reading",
    question: "Where did Maya go?  Passage: Last holiday, Maya visited a science museum with her class. She saw models of planets, a dinosaur skeleton, and a machine that showed how earthquakes happen. Her favorite part was the planet room.",
    options: { a: "A zoo", b: "A science museum", c: "A library", d: "A farm" },
    answer: "b",
    explanation: "Jawaban benar: B. A science museum (Reading)",
  },
  {
    id: 227,
    topic: "Reading",
    question: "Who went with Maya?  Passage: Last holiday, Maya visited a science museum with her class. She saw models of planets, a dinosaur skeleton, and a machine that showed how earthquakes happen. Her favorite part was the planet room.",
    options: { a: "Her family", b: "Her neighbors", c: "Her class", d: "Her cousins" },
    answer: "c",
    explanation: "Jawaban benar: C. Her class (Reading)",
  },
  {
    id: 228,
    topic: "Reading",
    question: "What did she see?  Passage: Last holiday, Maya visited a science museum with her class. She saw models of planets, a dinosaur skeleton, and a machine that showed how earthquakes happen. Her favorite part was the planet room.",
    options: { a: "Only paintings", b: "Models of planets and a dinosaur skeleton", c: "Only animals", d: "A football match" },
    answer: "b",
    explanation: "Jawaban benar: B. Models of planets and a dinosaur skeleton (Reading)",
  },
  {
    id: 229,
    topic: "Reading",
    question: "What did the machine demonstrate?  Passage: Last holiday, Maya visited a science museum with her class. She saw models of planets, a dinosaur skeleton, and a machine that showed how earthquakes happen. Her favorite part was the planet room.",
    options: { a: "Rain", b: "Wind", c: "Earthquakes", d: "Volcanoes" },
    answer: "c",
    explanation: "Jawaban benar: C. Earthquakes (Reading)",
  },
  {
    id: 230,
    topic: "Reading",
    question: "What was Maya's favorite part?  Passage: Last holiday, Maya visited a science museum with her class. She saw models of planets, a dinosaur skeleton, and a machine that showed how earthquakes happen. Her favorite part was the planet room.",
    options: { a: "The dinosaur room", b: "The planet room", c: "The cafeteria", d: "The gift shop" },
    answer: "b",
    explanation: "Jawaban benar: B. The planet room (Reading)",
  },
  {
    id: 231,
    topic: "Reading",
    question: "Where is Leo's garden?  Passage: Leo has a small garden behind his house. He grows tomatoes, carrots, and spinach. Every afternoon, he waters the plants. On weekends, his sister helps him remove weeds.",
    options: { a: "In front of his school", b: "Behind his house", c: "Beside a river", d: "On the roof" },
    answer: "b",
    explanation: "Jawaban benar: B. Behind his house (Reading)",
  },
  {
    id: 232,
    topic: "Reading",
    question: "Which vegetable does Leo grow?  Passage: Leo has a small garden behind his house. He grows tomatoes, carrots, and spinach. Every afternoon, he waters the plants. On weekends, his sister helps him remove weeds.",
    options: { a: "Potatoes only", b: "Tomatoes", c: "Rice", d: "Corn only" },
    answer: "b",
    explanation: "Jawaban benar: B. Tomatoes (Reading)",
  },
  {
    id: 233,
    topic: "Reading",
    question: "When does Leo water the plants?  Passage: Leo has a small garden behind his house. He grows tomatoes, carrots, and spinach. Every afternoon, he waters the plants. On weekends, his sister helps him remove weeds.",
    options: { a: "Every afternoon", b: "Every morning", c: "Every night", d: "Only on Sunday" },
    answer: "a",
    explanation: "Jawaban benar: A. Every afternoon (Reading)",
  },
  {
    id: 234,
    topic: "Reading",
    question: "Who helps him on weekends?  Passage: Leo has a small garden behind his house. He grows tomatoes, carrots, and spinach. Every afternoon, he waters the plants. On weekends, his sister helps him remove weeds.",
    options: { a: "His brother", b: "His father", c: "His sister", d: "His teacher" },
    answer: "c",
    explanation: "Jawaban benar: C. His sister (Reading)",
  },
  {
    id: 235,
    topic: "Reading",
    question: "What do they remove?  Passage: Leo has a small garden behind his house. He grows tomatoes, carrots, and spinach. Every afternoon, he waters the plants. On weekends, his sister helps him remove weeds.",
    options: { a: "Flowers", b: "Fruits", c: "Weeds", d: "Trees" },
    answer: "c",
    explanation: "Jawaban benar: C. Weeds (Reading)",
  },
  {
    id: 236,
    topic: "Reading",
    question: "Where did Nina find the kitten?  Passage: On Sunday morning, Nina found a lost kitten near the park. The kitten wore a blue collar. Nina asked a nearby security guard for help. Later, the owner came and thanked Nina for taking care of the kitten.",
    options: { a: "At school", b: "Near the park", c: "At the market", d: "At home" },
    answer: "b",
    explanation: "Jawaban benar: B. Near the park (Reading)",
  },
  {
    id: 237,
    topic: "Reading",
    question: "What color was the collar?  Passage: On Sunday morning, Nina found a lost kitten near the park. The kitten wore a blue collar. Nina asked a nearby security guard for help. Later, the owner came and thanked Nina for taking care of the kitten.",
    options: { a: "Red", b: "Green", c: "Blue", d: "Yellow" },
    answer: "c",
    explanation: "Jawaban benar: C. Blue (Reading)",
  },
  {
    id: 238,
    topic: "Reading",
    question: "Whom did Nina ask for help?  Passage: On Sunday morning, Nina found a lost kitten near the park. The kitten wore a blue collar. Nina asked a nearby security guard for help. Later, the owner came and thanked Nina for taking care of the kitten.",
    options: { a: "A teacher", b: "A doctor", c: "A security guard", d: "A shopkeeper" },
    answer: "c",
    explanation: "Jawaban benar: C. A security guard (Reading)",
  },
  {
    id: 239,
    topic: "Reading",
    question: "Who came later?  Passage: On Sunday morning, Nina found a lost kitten near the park. The kitten wore a blue collar. Nina asked a nearby security guard for help. Later, the owner came and thanked Nina for taking care of the kitten.",
    options: { a: "The kitten's owner", b: "Nina's teacher", c: "A police officer", d: "Nina's brother" },
    answer: "a",
    explanation: "Jawaban benar: A. The kitten's owner (Reading)",
  },
  {
    id: 240,
    topic: "Reading",
    question: "Why did the owner thank Nina?  Passage: On Sunday morning, Nina found a lost kitten near the park. The kitten wore a blue collar. Nina asked a nearby security guard for help. Later, the owner came and thanked Nina for taking care of the kitten.",
    options: { a: "She bought food.", b: "She took care of the kitten.", c: "She found a bicycle.", d: "She cleaned the park." },
    answer: "b",
    explanation: "Jawaban benar: B. She took care of the kitten. (Reading)",
  },
  {
    id: 241,
    topic: "Descriptive Text",
    question: "Read: 'My cat, Milo, has soft white fur and bright green eyes. He is small but very active.' What does Milo look like?",
    options: { a: "He has black fur.", b: "He has white fur and green eyes.", c: "He has brown eyes.", d: "He is very large." },
    answer: "b",
    explanation: "Jawaban benar: B. He has white fur and green eyes. (Descriptive Text)",
  },
  {
    id: 242,
    topic: "Descriptive Text",
    question: "Read: 'The library is quiet and clean. It has tall shelves filled with books.' How is the library?",
    options: { a: "Noisy and dirty", b: "Quiet and clean", c: "Dark and crowded", d: "Hot and messy" },
    answer: "b",
    explanation: "Jawaban benar: B. Quiet and clean (Descriptive Text)",
  },
  {
    id: 243,
    topic: "Descriptive Text",
    question: "Read: 'Mount Bromo is a beautiful mountain. Its surroundings are wide and sandy.' What is described?",
    options: { a: "A beach", b: "A mountain", c: "A library", d: "A garden" },
    answer: "b",
    explanation: "Jawaban benar: B. A mountain (Descriptive Text)",
  },
  {
    id: 244,
    topic: "Descriptive Text",
    question: "Read: 'The elephant is huge. It has large ears and a long trunk.' Which body part is mentioned?",
    options: { a: "Wings", b: "Long trunk", c: "Short tail", d: "Small ears" },
    answer: "b",
    explanation: "Jawaban benar: B. Long trunk (Descriptive Text)",
  },
  {
    id: 245,
    topic: "Descriptive Text",
    question: "Read: 'Our classroom has twenty desks, a whiteboard, and two windows.' How many desks are there?",
    options: { a: "Ten", b: "Fifteen", c: "Twenty", d: "Thirty" },
    answer: "c",
    explanation: "Jawaban benar: C. Twenty (Descriptive Text)",
  },
  {
    id: 246,
    topic: "Narrative Text",
    question: "Read: 'One day, a thirsty crow found a jar with a little water. The crow dropped small stones into the jar until the water rose.' What problem did the crow have?",
    options: { a: "It was hungry.", b: "It was thirsty.", c: "It was lost.", d: "It was cold." },
    answer: "b",
    explanation: "Jawaban benar: B. It was thirsty. (Narrative Text)",
  },
  {
    id: 247,
    topic: "Narrative Text",
    question: "What did the crow put into the jar?",
    options: { a: "Leaves", b: "Stones", c: "Flowers", d: "Sand" },
    answer: "b",
    explanation: "Jawaban benar: B. Stones (Narrative Text)",
  },
  {
    id: 248,
    topic: "Narrative Text",
    question: "Why did the water rise?",
    options: { a: "The jar broke.", b: "The stones raised the water level.", c: "It started raining.", d: "The crow drank it." },
    answer: "b",
    explanation: "Jawaban benar: B. The stones raised the water level. (Narrative Text)",
  },
  {
    id: 249,
    topic: "Narrative Text",
    question: "Read: 'A rabbit laughed at a slow turtle. They had a race. The turtle kept walking while the rabbit stopped to rest.' Who kept walking?",
    options: { a: "The rabbit", b: "The turtle", c: "Both stopped", d: "Neither" },
    answer: "b",
    explanation: "Jawaban benar: B. The turtle (Narrative Text)",
  },
  {
    id: 250,
    topic: "Narrative Text",
    question: "What lesson can the story teach?",
    options: { a: "Never study.", b: "Being steady and persistent can help you succeed.", c: "Always run fast.", d: "Never help others." },
    answer: "b",
    explanation: "Jawaban benar: B. Being steady and persistent can help you succeed. (Narrative Text)",
  },
  {
    id: 251,
    topic: "Functional Text",
    question: "Announcement: 'The English club meeting will be held on Friday at 2 p.m. in Room 5.' When is the meeting?",
    options: { a: "Thursday", b: "Friday at 2 p.m.", c: "Friday at 5 p.m.", d: "Monday" },
    answer: "b",
    explanation: "Jawaban benar: B. Friday at 2 p.m. (Functional Text)",
  },
  {
    id: 252,
    topic: "Functional Text",
    question: "Where will the English club meeting be held?",
    options: { a: "Room 2", b: "Room 3", c: "Room 5", d: "The library" },
    answer: "c",
    explanation: "Jawaban benar: C. Room 5 (Functional Text)",
  },
  {
    id: 253,
    topic: "Functional Text",
    question: "Sign: 'KEEP OFF THE GRASS.' What should you do?",
    options: { a: "Walk on the grass.", b: "Do not walk on the grass.", c: "Water the grass.", d: "Pick the grass." },
    answer: "b",
    explanation: "Jawaban benar: B. Do not walk on the grass. (Functional Text)",
  },
  {
    id: 254,
    topic: "Functional Text",
    question: "Notice: 'Please return library books within seven days.' What should students do?",
    options: { a: "Keep books forever.", b: "Return books within seven days.", c: "Buy new books.", d: "Throw books away." },
    answer: "b",
    explanation: "Jawaban benar: B. Return books within seven days. (Functional Text)",
  },
  {
    id: 255,
    topic: "Functional Text",
    question: "Message: 'Mom, I went to the bakery. I will be home at 5 p.m. —Rina.' Where did Rina go?",
    options: { a: "Hospital", b: "Bakery", c: "School", d: "Library" },
    answer: "b",
    explanation: "Jawaban benar: B. Bakery (Functional Text)",
  },
  {
    id: 256,
    topic: "Writing Basics",
    question: "Choose the best sentence.",
    options: { a: "Every day school I go.", b: "I go to school every day.", c: "Go I school every day.", d: "Every I day go school." },
    answer: "b",
    explanation: "Jawaban benar: B. I go to school every day. (Writing Basics)",
  },
  {
    id: 257,
    topic: "Writing Basics",
    question: "Choose the correct order: 'is / my / This / book.'",
    options: { a: "My this is book.", b: "This is my book.", c: "Book is this my.", d: "This my book is." },
    answer: "b",
    explanation: "Jawaban benar: B. This is my book. (Writing Basics)",
  },
  {
    id: 258,
    topic: "Writing Basics",
    question: "Choose the best sentence.",
    options: { a: "She likes reading books.", b: "She like reading books.", c: "She liking books.", d: "She liked read books every day." },
    answer: "a",
    explanation: "Jawaban benar: A. She likes reading books. (Writing Basics)",
  },
  {
    id: 259,
    topic: "Writing Basics",
    question: "Choose the correct question.",
    options: { a: "Where you live?", b: "Where do you live?", c: "Where does you live?", d: "Where living you?" },
    answer: "b",
    explanation: "Jawaban benar: B. Where do you live? (Writing Basics)",
  },
  {
    id: 260,
    topic: "Writing Basics",
    question: "Choose the best sentence using 'because'.",
    options: { a: "I stayed home because it was raining.", b: "Because raining I home.", c: "I because stayed raining.", d: "It raining because home." },
    answer: "a",
    explanation: "Jawaban benar: A. I stayed home because it was raining. (Writing Basics)",
  },
  {
    id: 261,
    topic: "Vocabulary",
    question: "The opposite of 'expand' is ...",
    options: { a: "increase", b: "grow", c: "shrink", d: "build" },
    answer: "c",
    explanation: "Jawaban benar: C. shrink (Vocabulary)",
  },
  {
    id: 262,
    topic: "Vocabulary",
    question: "A 'spectator' is someone who ...",
    options: { a: "watches an event", b: "cooks food", c: "drives a bus", d: "writes books" },
    answer: "a",
    explanation: "Jawaban benar: A. watches an event (Vocabulary)",
  },
  {
    id: 263,
    topic: "Vocabulary",
    question: "If a person is 'curious', they want to ...",
    options: { a: "know or learn something", b: "sleep all day", c: "avoid questions", d: "run quickly" },
    answer: "a",
    explanation: "Jawaban benar: A. know or learn something (Vocabulary)",
  },
  {
    id: 264,
    topic: "Vocabulary",
    question: "The word 'accurate' means ...",
    options: { a: "correct", b: "ancient", c: "expensive", d: "dangerous" },
    answer: "a",
    explanation: "Jawaban benar: A. correct (Vocabulary)",
  },
  {
    id: 265,
    topic: "Vocabulary",
    question: "A 'destination' is ...",
    options: { a: "the place you are going to", b: "a kind of vehicle", c: "a school uniform", d: "a meal" },
    answer: "a",
    explanation: "Jawaban benar: A. the place you are going to (Vocabulary)",
  },
  {
    id: 266,
    topic: "Vocabulary",
    question: "The opposite of 'generous' is ...",
    options: { a: "kind", b: "selfish", c: "helpful", d: "friendly" },
    answer: "b",
    explanation: "Jawaban benar: B. selfish (Vocabulary)",
  },
  {
    id: 267,
    topic: "Vocabulary",
    question: "Someone who works in a restaurant and serves food is a ...",
    options: { a: "waiter", b: "pilot", c: "farmer", d: "scientist" },
    answer: "a",
    explanation: "Jawaban benar: A. waiter (Vocabulary)",
  },
  {
    id: 268,
    topic: "Vocabulary",
    question: "'Predict' means ...",
    options: { a: "guess what may happen", b: "forget the past", c: "clean a room", d: "draw a picture" },
    answer: "a",
    explanation: "Jawaban benar: A. guess what may happen (Vocabulary)",
  },
  {
    id: 269,
    topic: "Grammar",
    question: "Neither of the answers ___ correct.",
    options: { a: "are", b: "is", c: "am", d: "be" },
    answer: "b",
    explanation: "Jawaban benar: B. is (Grammar)",
  },
  {
    id: 270,
    topic: "Grammar",
    question: "My sister and I ___ ready for school.",
    options: { a: "is", b: "am", c: "are", d: "be" },
    answer: "c",
    explanation: "Jawaban benar: C. are (Grammar)",
  },
  {
    id: 271,
    topic: "Grammar",
    question: "The boys ___ their homework every evening.",
    options: { a: "does", b: "do", c: "doing", d: "did" },
    answer: "b",
    explanation: "Jawaban benar: B. do (Grammar)",
  },
  {
    id: 272,
    topic: "Grammar",
    question: "She has ___ umbrella.",
    options: { a: "a", b: "an", c: "many", d: "some" },
    answer: "b",
    explanation: "Jawaban benar: B. an (Grammar)",
  },
  {
    id: 273,
    topic: "Grammar",
    question: "There ___ some milk in the glass.",
    options: { a: "are", b: "am", c: "is", d: "be" },
    answer: "c",
    explanation: "Jawaban benar: C. is (Grammar)",
  },
  {
    id: 274,
    topic: "Grammar",
    question: "Which sentence is correct?",
    options: { a: "He can sings.", b: "He can sing.", c: "He can singing.", d: "He can to sing." },
    answer: "b",
    explanation: "Jawaban benar: B. He can sing. (Grammar)",
  },
  {
    id: 275,
    topic: "Tenses",
    question: "Last night, we ___ dinner at home.",
    options: { a: "have", b: "has", c: "had", d: "having" },
    answer: "c",
    explanation: "Jawaban benar: C. had (Tenses)",
  },
  {
    id: 276,
    topic: "Tenses",
    question: "Every morning, the teacher ___ the attendance.",
    options: { a: "check", b: "checks", c: "checked", d: "checking" },
    answer: "b",
    explanation: "Jawaban benar: B. checks (Tenses)",
  },
  {
    id: 277,
    topic: "Tenses",
    question: "Yesterday, Ani ___ her room.",
    options: { a: "cleans", b: "clean", c: "cleaned", d: "cleaning" },
    answer: "c",
    explanation: "Jawaban benar: C. cleaned (Tenses)",
  },
  {
    id: 278,
    topic: "Tenses",
    question: "My brother ___ cartoons every weekend.",
    options: { a: "watch", b: "watches", c: "watched", d: "watching" },
    answer: "b",
    explanation: "Jawaban benar: B. watches (Tenses)",
  },
  {
    id: 279,
    topic: "Tenses",
    question: "Two days ago, they ___ to Bandung.",
    options: { a: "travel", b: "travels", c: "traveled", d: "traveling" },
    answer: "c",
    explanation: "Jawaban benar: C. traveled (Tenses)",
  },
  {
    id: 280,
    topic: "Tenses",
    question: "My father ___ tea every afternoon.",
    options: { a: "drink", b: "drinks", c: "drank", d: "drinking" },
    answer: "b",
    explanation: "Jawaban benar: B. drinks (Tenses)",
  },
  {
    id: 281,
    topic: "Pronouns",
    question: "Lisa and I finished the work. ___ were tired.",
    options: { a: "We", b: "They", c: "She", d: "He" },
    answer: "a",
    explanation: "Jawaban benar: A. We (Pronouns)",
  },
  {
    id: 282,
    topic: "Pronouns",
    question: "The boys brought ___ football.",
    options: { a: "their", b: "theirs", c: "them", d: "they" },
    answer: "a",
    explanation: "Jawaban benar: A. their (Pronouns)",
  },
  {
    id: 283,
    topic: "Pronouns",
    question: "That red bicycle is ___. I bought it.",
    options: { a: "me", b: "my", c: "mine", d: "I" },
    answer: "c",
    explanation: "Jawaban benar: C. mine (Pronouns)",
  },
  {
    id: 284,
    topic: "Pronouns",
    question: "Mr. Andi is our teacher. We listen to ___.",
    options: { a: "he", b: "him", c: "his", d: "they" },
    answer: "b",
    explanation: "Jawaban benar: B. him (Pronouns)",
  },
  {
    id: 285,
    topic: "Modals",
    question: "You ___ use a dictionary during this test. It is not allowed.",
    options: { a: "must", b: "mustn't", c: "can", d: "may" },
    answer: "b",
    explanation: "Jawaban benar: B. mustn't (Modals)",
  },
  {
    id: 286,
    topic: "Modals",
    question: "___ you please close the door?",
    options: { a: "Could", b: "Mustn't", c: "May not", d: "Needn't" },
    answer: "a",
    explanation: "Jawaban benar: A. Could (Modals)",
  },
  {
    id: 287,
    topic: "Modals",
    question: "We ___ save water to protect the environment.",
    options: { a: "should", b: "shouldn't", c: "can't", d: "mustn't" },
    answer: "a",
    explanation: "Jawaban benar: A. should (Modals)",
  },
  {
    id: 288,
    topic: "Modals",
    question: "Visitors ___ take photos here if the sign says 'No Photography.'",
    options: { a: "can", b: "may", c: "mustn't", d: "should" },
    answer: "c",
    explanation: "Jawaban benar: C. mustn't (Modals)",
  },
  {
    id: 289,
    topic: "Reading",
    question: "Read: 'Fajar packed an umbrella because the sky was dark and cloudy.' Why did Fajar pack an umbrella?",
    options: { a: "He expected rain.", b: "He wanted to play.", c: "He was going swimming.", d: "He lost his bag." },
    answer: "a",
    explanation: "Jawaban benar: A. He expected rain. (Reading)",
  },
  {
    id: 290,
    topic: "Reading",
    question: "Read: 'Lina saved part of her allowance for three months. Then she bought a storybook.' What did Lina save?",
    options: { a: "Her homework", b: "Her allowance", c: "Her lunch", d: "Her toys" },
    answer: "b",
    explanation: "Jawaban benar: B. Her allowance (Reading)",
  },
  {
    id: 291,
    topic: "Descriptive Text",
    question: "Read: 'The beach has soft white sand, clear blue water, and tall palm trees.' Which feature is mentioned?",
    options: { a: "Snowy hills", b: "White sand", c: "Large buildings", d: "Cold weather" },
    answer: "b",
    explanation: "Jawaban benar: B. White sand (Descriptive Text)",
  },
  {
    id: 292,
    topic: "Descriptive Text",
    question: "Read: 'My grandfather's house is old but comfortable. It has a large wooden door.' What is the door made of?",
    options: { a: "Glass", b: "Metal", c: "Wood", d: "Plastic" },
    answer: "c",
    explanation: "Jawaban benar: C. Wood (Descriptive Text)",
  },
  {
    id: 293,
    topic: "Narrative Text",
    question: "Read: 'A fox saw grapes hanging high above him. He tried to reach them but failed.' What did the fox try to reach?",
    options: { a: "Apples", b: "Grapes", c: "Berries", d: "Leaves" },
    answer: "b",
    explanation: "Jawaban benar: B. Grapes (Narrative Text)",
  },
  {
    id: 294,
    topic: "Narrative Text",
    question: "Read: 'The little girl found a wallet and gave it to the police. Later, the owner came to claim it.' What did the girl find?",
    options: { a: "A key", b: "A wallet", c: "A book", d: "A phone" },
    answer: "b",
    explanation: "Jawaban benar: B. A wallet (Narrative Text)",
  },
  {
    id: 295,
    topic: "Functional Text",
    question: "Sign: 'WASH YOUR HANDS.' What is the instruction?",
    options: { a: "Dry your shoes.", b: "Wash your hands.", c: "Open the window.", d: "Wear a hat." },
    answer: "b",
    explanation: "Jawaban benar: B. Wash your hands. (Functional Text)",
  },
  {
    id: 296,
    topic: "Functional Text",
    question: "Announcement: 'The school library is closed on Monday for cleaning.' When is it closed?",
    options: { a: "Sunday", b: "Monday", c: "Tuesday", d: "Friday" },
    answer: "b",
    explanation: "Jawaban benar: B. Monday (Functional Text)",
  },
  {
    id: 297,
    topic: "Writing Basics",
    question: "Choose the correct sentence.",
    options: { a: "They goes to school.", b: "They go to school.", c: "They going school.", d: "They is go school." },
    answer: "b",
    explanation: "Jawaban benar: B. They go to school. (Writing Basics)",
  },
  {
    id: 298,
    topic: "Writing Basics",
    question: "Choose the best sentence.",
    options: { a: "Yesterday I visited my aunt.", b: "Yesterday I visit my aunt every day.", c: "Yesterday I visiting my aunt.", d: "Yesterday I visits my aunt." },
    answer: "a",
    explanation: "Jawaban benar: A. Yesterday I visited my aunt. (Writing Basics)",
  },
  {
    id: 299,
    topic: "Vocabulary",
    question: "If a task is 'difficult', it is ...",
    options: { a: "easy", b: "hard", c: "short", d: "empty" },
    answer: "b",
    explanation: "Jawaban benar: B. hard (Vocabulary)",
  },
  {
    id: 300,
    topic: "Grammar",
    question: "Choose the correct sentence.",
    options: { a: "She have two cats.", b: "She has two cats.", c: "She having two cats.", d: "She haves two cats." },
    answer: "b",
    explanation: "Jawaban benar: B. She has two cats. (Grammar)",
  },];

export const ESSAY_QUESTIONS: Essay[] = [
  {
    id: 31,
    topic: "Writing Basics",
    prompt:
      "Arrange these words into a good sentence: 'to - school - every - Rani - goes - day'. Write your full sentence!",
    hint: "Tulis satu kalimat lengkap dengan huruf kapital dan tanda titik.",
    keywords: ["rani", "goes", "to", "school", "every", "day"],
    sample: "Rani goes to school every day.",
  },
  {
    id: 32,
    topic: "Descriptive Text",
    prompt:
      "Write 2-3 sentences describing your best friend (name, appearance, and one thing he/she likes).",
    hint: "Gunakan Present Tense, contoh: 'My best friend is ... He has ... He likes ...'",
    keywords: ["friend", "is", "has", "likes", "he", "she", "my"],
    sample: "My best friend is Dika. He has short black hair and a friendly smile. He likes playing football.",
  },
];

export const QUIZ_DURATION_SECONDS = 30 * 60;

/** Auto-scoring uraian: maksimal 10 poin per soal berdasarkan kata kunci + kelengkapan. */
export function scoreEssay(essay: Essay, answer: string): number {
  const text = answer.toLowerCase().trim();
  if (text.length < 3) return 0;
  const words = text.replace(/[^a-z\s']/g, " ").split(/\s+/).filter(Boolean);
  const hits = essay.keywords.filter((k) => words.includes(k)).length;
  let score = (hits / essay.keywords.length) * 8;
  if (words.length >= (essay.id === 31 ? 5 : 10)) score += 1;
  if (/^[A-Z]/.test(answer.trim()) && /[.!?]$/.test(answer.trim())) score += 1;
  return Math.max(0, Math.min(10, Math.round(score)));
}

/** Pilih sejumlah soal secara acak dari setiap kategori */
export function pickRandomByCategory(
  questions: MCQ[],
  perCategory: number
): MCQ[] {
  // Kelompokkan soal berdasarkan kategori
  const byCategory = new Map<string, MCQ[]>();
  for (const q of questions) {
    const list = byCategory.get(q.topic) || [];
    list.push(q);
    byCategory.set(q.topic, list);
  }

  // Fisher-Yates shuffle
  const shuffle = <T>(arr: T[]): T[] => {
    const a = [...arr];
    for (let i = a.length - 1; i > 0; i--) {
      const j = Math.floor(Math.random() * (i + 1));
      [a[i]!, a[j]!] = [a[j]!, a[i]!];
    }
    return a;
  };

  // Ambil n soal per kategori, lalu shuffle hasilnya
  const picked: MCQ[] = [];
  for (const [, list] of byCategory) {
    const shuffled = shuffle(list);
    picked.push(...shuffled.slice(0, Math.min(perCategory, shuffled.length)));
  }
  return shuffle(picked);
}
